version: "3.9"

services:
  telemetry-pipeline:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: hybrid-telemetry-pipeline
    restart: unless-stopped
    ports:
      - "8080:8080" # Health probes (/healthz, /readyz)
      - "9102:9102" # Prometheus exposition (/metrics)
    environment:
      - PIPELINE_ENVIRONMENT=local-docker
      - PIPELINE_LOG_LEVEL=INFO
      - PIPELINE_SAMPLING_RATE_HZ=100.0
      - PIPELINE_WINDOW_SIZE=128
      - PIPELINE_NUM_CHANNELS=4
      - PIPELINE_INJECT_ANOMALIES=true
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m
    networks:
      - telemetry-net

  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: telemetry-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../observability/prometheus/rules:/etc/prometheus/rules:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-lifecycle"
    networks:
      - telemetry-net
    depends_on:
      - telemetry-pipeline

  grafana:
    image: grafana/grafana:10.2.3
    container_name: telemetry-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin_sre_portfolio
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - ../observability/grafana/provisioning:/etc/grafana/provisioning:ro
      - ../observability/grafana/dashboards:/var/lib/grafana/dashboards:ro
    networks:
      - telemetry-net
    depends_on:
      - prometheus

networks:
  telemetry-net:
    driver: bridge
